version: 0.0
os: linux

files:
  - source: /
    destination: /home/ec2-user/my-server

permissions:
  - object: /home/ec2-user/my-server
    pattern: "**"
    owner: ec2-user
    group: ec2-user
  - object: /home/ec2-user/my-server
    owner: ec2-user
    group: ec2-user
    type: 
      - folder

hooks:
      
  ApplicationStart:
    - location: scripts/applicationStart.sh
      timeout: 800
      runas: ec2-user
