version: 0.0
os: linux

files:
  - source: /
    destination: /home/ec2-user/my-server

hooks:
      
  ApplicationStart:
    - location: scripts/applicationStart.sh
      timeout: 800
      runas: root
