version: 0.0
os: linux

files:
  - source: /server
    destination: /home/ec2-user/clinic-server

hooks:
      
  ApplicationStart:
    - location: clinic-server/scripts/changePermission.sh
      timeout: 800
      runas: root
    - location: clinic-server/scripts/applicationStart.sh
      timeout: 800
      runas: ec2-user
